### ISSUE TITLE
"About" page?

### ISSUE THREAD

**Issue by Bentheburrito** [Bentheburrito/sacastats#103]
I was thinking we should link the GitHub somewhere, and an about page came to mind. Maybe we could include changelogs there too? Curious for thoughts @dm0896665

**Comment by dm0896665** [comment]
Yeah, we can either have like a "View current progress" section with a link to GitHub at the bottom of the change logs or just create an about page. Either way sounds good!

**Comment by Bentheburrito** [comment]
Actually I think I like that idea better - I think the home page already gives a good overview of the site that an About page would just be repeating. A link to the GitHub in the change logs sounds good to me!
