### ISSUE TITLE
Clean Model loading

### ISSUE THREAD

**Issue by dm0896665** [Bentheburrito/sacastats#104]
Model loads after the loading spinner has been gone for a while. Make the transition smoother.

**Comment by Bentheburrito** [comment]
suggestion for this: maybe have another little SaCa Stats Logo spinning where the character is until it's loaded?

**Comment by dm0896665** [comment]
I can, but IMO I thought that it looked smoother/ more professional to have the bootstrap spinner.

**Comment by dm0896665** [comment]
I pushed an example of what it would look like with the Saca loader instead. Which do you think is better?

**Comment by Bentheburrito** [comment]
Hmm now that I see it I think I agree with you, the bootstrap one fits in better

**Comment by dm0896665** [comment]
Okay, will revert now.
