### ISSUE TITLE
Redo ESS Reconnection Logic

### ISSUE THREAD

**Issue by Bentheburrito** [Bentheburrito/sacastats#107]
It's well known that ESS tends to randomly stop sending events. There's lots of discussion around it in the #api-dev channel of the Planetside 2 Discord. We need SacaStats to be more robust in terms of detecting a lack of events and resubscribing/reconnecting to ESS. 

It might be worth registering a couple of different service IDs and running 2+ ESS connections. The connections can cross reference events with each other, and using supervision trees, automatically kill/restart flaky connections. I think some additional application-level deduplication will be needed, since I don't think it's a good idea to rely on the database to dedup based on primary keys for literally every event that comes in.

Below are some links/images I found insightful/useful when it comes to implementing this.

1. https://discord.com/channels/251073753759481856/451032574538547201/985435831835688960
2. ![image](https://user-images.githubusercontent.com/33915719/174452941-c68a7e1a-9c27-4440-8297-0b762440208a.png)
3. https://discord.com/channels/251073753759481856/451032574538547201/867134257917984819
4. https://discord.com/channels/251073753759481856/451032574538547201/985358084958478366
5. https://discord.com/channels/251073753759481856/451032574538547201/985695427737309184

**Comment by dm0896665** [comment]
Looks like a good plan

**Comment by Bentheburrito** [comment]
Step-by-step outline:
- [ ] Create an `EventTrackerSupervisor` (`DynamicSupervisor`), responsible for monitoring the health of `EventTracker`s (ETs). 
This supervisor will be started in the application supervision tree, and spin up a configurable number of ETs (perhaps a new NUM_EVENT_TRACKERS env var). On top of usual OTP supervisor duties, this supervisor will be responsible for monitoring the health of each ET connection, via a report of some kind that each ET sends the supervisor. The report can contain data points like: total number of each event within a time interval, a MapSet of hashed events (note link 5. above, where using time-based fields to hash an event could be troublesome), and maybe a health-check poll with ESS based on link 1. The supervisor will have a configurable margin of error for each data point in this report, where if an ETs report falls outside this margin compared to the majority of ETs (or, especially in the case of 2 ETs, the report which contains less information in each data point*), that ET is killed and restarted.
- [ ] Create an SID distributor, and a pool of SIDs to distribute among the ETs (probably falls under responsibilities of the `EventTrackerSupervisor`).
- [ ] Create a de-duplicator, which consumes and dedups events from the active ETs, eventually inserting a single event to the DB. I think keeping the primary-key constraints that prevent most duplicate events in the DB is fine for now (and will even double-check the work of the deduper), unless the index sizes become a problem. For high-frequency events like Vehicle Repair GainExperience, identifying which ET the event came from will probably be necessary to greatly reduce over-deduplication. However, if duplicate events are coming from the same stream, that could produces duplicates that slip by the deduper.
- [ ] Rework `EventTracker` to pass events to the deduper, instead of inserting directly to the DB. ETs also need to store information about the events they consume to generate reports to the ET Supervisor.

*for example, say there are two ETs running, and the ET Supervisor has a margin of 5 on player events. If ET 1 reports it received 15 PlayerFacilityCapture events, but ET 2 reported only 9, ET 2 falls outside the margin of error for that event type, and so is restarted.

**Comment by Bentheburrito** [comment]
Thoughts for myself while implementing this.

**NOTE**: the following would only theoretically work if there aren't any duplicate events *within the same ESS connection*. If there are dups in the same stream, those would be counted as legitimate with the strategy outlined below.

Another way to go about deduping: have two maps in state, first is `event_hash => event`, and second is `event_hash => %{received_at_timestamp => event_tracker_pid}`. This way, we can assert whether we've received a given event before (by checking if an entry with event_hash exists in the second map), AND who exactly gave us the event previously, as well as the timestamp when we received it. With those last 2 bits of info, we can 
1. run an interval task that clears out old entries (if received_at_timestamp < cur_timestamp - some_offset, this is old and we can remove it), and 
2. determine if the given event is actually a duplicate or just another event with the same hash, as is often the case with high-frequency events like GainExperience Vehicle Repair. (e.g. if we get an event from ET1, and see that we previously got an event with the same hash, but it was also received by ET1, then this must be a different event.)
