### ISSUE TITLE
Some client-side/JS features don't apply to LiveView-updated DOM elements

### ISSUE THREAD

**Issue by Bentheburrito** [Bentheburrito/sacastats#140]
When applying our custom `date-time` class to format dates to the user's timezone, I noticed that dates added by LiveView after the initial page load aren't formatted. I think this is because the `formatDateTimes` JS fn only runs on page load. To fix this, I think we could use Phoenix [client hooks](https://hexdocs.pm/phoenix_live_view/js-interop.html#client-hooks-via-phx-hook) to run some JS whenever the server adds/updates DOM elements with the `date-time` class

**Comment by Bentheburrito** [comment]
Another potential solution: Maybe on LiveView mount, the client passes the timezone as an attribute, and we can render dates in their timezone server-side without calling additional JS

**Comment by dm0896665** [comment]
> Another potential solution: Maybe on LiveView mount, the client passes the timezone as an attribute, and we can render dates in their timezone server-side without calling additional JS

I thought the whole point of the JS time conversions was due to elixir not being able to handle time zones

**Comment by Bentheburrito** [comment]
The only thing missing from the Elixir side is the user's timezone, so if the browser can give that to the backend somehow, then we could render the dates properly

**Comment by dm0896665** [comment]
Oh, then I would like that solution a lot better then if we can figure it out
