### ISSUE TITLE
Update discord user styles on front end.

### ISSUE THREAD

**Issue by dm0896665** [Bentheburrito/sacastats#17]
Make smaller and more web responsive.

**Comment by Krish-bhardwaj** [comment]
Hey, @dm0896665  I would like to work on this issue since I'm new to opensource contribution 
 don't know from where to start. Can you please assign this to me as I have to get started :)

**Comment by dm0896665** [comment]
> Hey, @dm0896665 I would like to work on this issue since I'm new to opensource contribution don't know from where to start. Can you please assign this to me as I have to get started :)

Hey, @Krish-bhardwaj we are currently not having any outside contributions on this project. If you would like to find a spot to start you could try looking into this repo/ issue: https://github.com/Sub6Resources/flutter_html/issues/62 **Note that it's tagged with a **good first issue** tag. Lots of repositories have tags like this, so if you are not a fan of that one you can look more into other ones and really search for that tag. And if you are looking into other open-source HTML/CSS projects to help build your portfolio try this site out https://awesomeopensource.com/projects/html-css Sorry again, and good luck out there! :D
