### ISSUE TITLE
Poll system for new-member voting

### ISSUE THREAD

**Issue by Bentheburrito** [Bentheburrito/sacastats#24]
A poll system for outfit-related decision-making, like voting in new members.

A logged-in user should be able to navigate to a page for creating a custom poll. Polls will have the following properties:
- A title/prompt describing what the poll is for.
- Multiple-choice responses and/or essay response text-boxes.
- An option for the poll-maker to only allow logged-in users to vote.
- An option for the poll-maker to whitelist certain user IDs for voting.
- An option for the poll-taker to vote anonymously (only available if the poll-maker did not use the two options above.)

The poll-maker will be able to view the results as they come in, and a poll-taker can view the results after voting (but cannot see who voted for what.)

This is the MVP for now - more functionality like Discord integration (voting via Discord application commands), linking users to an outfit and whitelisting them to a poll automatically, poll expiration times, etc. could be prompted in future issues.

@dm0896665 Does this look good to you? Anything to add/change?

**Comment by dm0896665** [comment]
I think this looks good, I honestly really like the quick vote through discord option, but could be rough for longer polls, not sure though.
