### ISSUE TITLE
Set a standard for "character" spelling

### ISSUE THREAD

**Issue by dm0896665** [Bentheburrito/sacastats#28]
The URL says 'character', but the navigation buttons say 'Characters'. 
Should We keep with 'character' or 'characters'? 

I just feel like it should stay consistent throughout the site.

**Comment by Bentheburrito** [comment]
Imo I don't think it matters too much, but if I were to pick one, I'd go with singular "character"

**Comment by dm0896665** [comment]
The only reason is I know at least for me it's kind of nice to have the "steps" to a certain web page in the URL so you can make them on your own from memory a bit easier by just writing the "steps" to get there. (Example: I press character then type my character name so the path would be '/character/mycharactername'). It's not too big of a deal though. I also think "character" would be the way to go though.

**Comment by Bentheburrito** [comment]
yeah that makes sense, I can definitely see that helpful when someone's looking through say their browser history and the URL can tell them exactly which page it leads to
