### ISSUE TITLE
Add image_id and image_path to `weapons.json` static data, filter out extra double quotes

### ISSUE THREAD

**Issue by Bentheburrito** [Bentheburrito/sacastats#35]
The script should fetch the `image_path` and `image_id` fields from the census and aggregate with the sanction weapon data fetched from the community census repo. The script should also filter out the extra double quotes found in weapon names that contain double quotes.

**Comment by Bentheburrito** [comment]
Also, the script should filter out the excessive quotes in some weapon names (e.g. `"NS-357 ""Endeavor"" Underboss"`)

**Comment by dm0896665** [comment]
So will this remove it to be `NS-357 "Endeavor" Underboss` or `NS-357 Endeavor Underboss`

**Comment by Bentheburrito** [comment]
The former - just have to figure out the regex first :stuck_out_tongue:
