### ISSUE TITLE
Weapon stats aren't sorted by selected column upon search

### ISSUE THREAD

**Issue by Bentheburrito** [Bentheburrito/sacastats#37]
When using the "Search Weapon Name" search bar at the character weapon page, the selected column sort is not applied. I think (hope) this is as simple a fix as calling a JS function on page load.

**To Reproduce**
1. Lookup any character and select the "Weapons" tab
2. Sort by one of the columns (e.g. "Acc")
2a. Note that the rows are properly sorted by the column
3. Use the search bar to look up any weapon (as long as it returns multiple rows)
4. See that while the correct rows are returned, they are not ordered by the selected column
4a. A workaround is to click the column twice to properly sort the rows.

**Comment by dm0896665** [comment]
Yes, this should be an easy fix and the workaround is kind of my hack solution.
`function updateSortTable() {
        if (!didTableRecieveStyleUpdate()) {
            let toSortDesc = table.querySelector(".desc");
            let toSortAsc = table.querySelector(".asc");

            if (toSortDesc != undefined) {
                toSortDesc.click();
                toSortDesc.click();
            } else if (toSortAsc != undefined) {
                toSortAsc.click();
                toSortAsc.click();
            }
        }
    }`
