### ISSUE TITLE
Session Tracker and Page

### ISSUE THREAD

**Issue by Bentheburrito** [Bentheburrito/sacastats#49]
I'm thinking about working on the session tracker next, and wanted to share some ideas I had for it, and hopefully get some of your own, @dm0896665.

Currently we store "sessions" as an aggregation of a player's activity (kills, xp earned, etc.) from login to logout as a record in the DB. I think the general layout of the page should have:
- List of all sessions available to view (page lands on most recent session)
- If the player is online, the current session is available to be viewed and is updated live. Individual events are displayed as they come in.
- non-MVP goal: when a session ends, generate a path on the continent map that shows where the player went (obviously we don't do this for a current/live session, as that would allow people to be tracked).

**Comment by dm0896665** [comment]
Okay, that would be SUPER cool to have a path-type thing, but at the same time, I think it would be a bit hard to do lol. I think how you have it in your head is pretty good. 

I would make a note that something discord bot shows that is pretty cool is the ability to see how many kills were with what weapons (e.g. Needler x3; Dalton x1) same with deaths. 

Another thing could be to show the number of revives as well. I'm not sure about the events, but we could query thier current deaths at the beginning and ending and it should show us the number of revives and we can then show actual vs kept KDR and things like that. 

I also think it would be cool to have number of medkits used to see how many of those people use per session. Not sure if you can get something like that, but I think I did see something like that in a total stats page someone had so they must have got it somewhere

**Comment by Bentheburrito** [comment]
Yeahhh I agree, definitely something for later down the road, maybe in 2.0? Also, since we don't know coordinates of players, only facilities where there is activity, a heat-map of hexes by player activity might be better than a path.

Ooo nice thought! The thing is we current only store kills and deaths by an integer. However, I think that could pretty easily be changed to something like how we store vehicles_destroyed and vehicles_lost, where it's a map %{vehicle name => number killed/lost}, except of course we use weapon names (or IDs?) instead of vehicle names.

Number of revives is great! We can know when someone's revived via GainExperience events as well

# of medkits (or really any item used) sounds cool as well, though I don't know if ESS gives us that info, but if you point me to where you saw that stats page I can take a look at that too
