### ISSUE TITLE
Character Cache

### ISSUE THREAD

**Issue by Bentheburrito** [Bentheburrito/sacastats#55]
A cache for basic character info (name, faction ID) would be good because:
- We'd hit the Census less for repeated accesses of this basic info.
- Much quicker access to this info after the first fetch.

I think a simple GenServer that maps the character ID to the info will do for now. Later it may be worth it to additionally persist the info to the DB, and let records periodically expire (at which point we'd have to hit the Census again to refresh the character's info, as in the rare case of name changes).

@dm0896665 any thoughts?

**Comment by dm0896665** [comment]
Looks good to me. How do we want to go about storing the data from saves? I mean like if we save all data at a certain time for one player. How do we go about saving it for others around the same time without duplicate data, but still retaining the time for each character's save? I guess we can look for log-in/out events up just thinking logic-wise.

**Comment by Bentheburrito** [comment]
You mean for session saves? How exactly are you thinking of going about it? If we save the specific events that make up a session, I don't think duplication would be of concern. My initial thought would be to put a boolean column like "isExpirable" on the event tables, where "true" means the event is a part of a saved session. The thing is that would be another column that takes up space, where most of the values will be "false" anyway (since most sessions aren't going to be saved).

**Comment by dm0896665** [comment]
Well, it should only take up 1 bit (0 or 1 for true or false), but I was wondering if they were to want to keep a session how would we look at getting that data back. I'm not really sure how to go about it

**Comment by Bentheburrito** [comment]
Ah you're right, I wasn't thinking with actual numbers lol. I'll open a new issue that outlines my vague idea of what saving sessions looks like (I think this is a bit off topic for the cache)
