### ISSUE TITLE
Create the character stat page

### ISSUE THREAD

**Issue by dm0896665** [Bentheburrito/sacastats#63]
This will contain general less graphical stats associated with the character (such as total kills deaths, auraxiums, etc)

This should pair up with the general page as it will use the same model rendered there. Use JS to display either the graphical or less graphical stats based on the url.

**Comment by dm0896665** [comment]
@Bentheburrito Would you be able to write the backend for this to get the data you want to be shown, then I can write up all the js and style it?

**Comment by Bentheburrito** [comment]
Yeah I can do that. Is there any specific data/collections you want included?

**Comment by dm0896665** [comment]
I'm not 100% really. Just add extra stats that you think might be interesting. These are from the official site to give you some ideas

Kills, Deaths, K/D Ratio, Assists, Facility Captures, Facilities Defended, Score, Total Time Played, Enemy Vehicles Destroyed, Medal Count, Infantry Accuracy, Infantry Shots Fired, Infantry Shots Hit, Vehicle Accuracy, Vehicle Shots Fired, Vehicle Shots Hit

One thing that I think would be cool is to have medal count by type (5 Aurax, 3 Gold, 2 silver...)

**Comment by Bentheburrito** [comment]
Going to close this for now as we're planning on keeping this info/adding more to the general stats page - might bring this back if it gets too convoluted though
